version: "3.9"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=salesreportsapi"
      - "POSTGRES_PASSWORD=12345678"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - /.docker/postgresql:/var/lib/postgresql/salesreportsapi
    logging:
      options:
        max-size: 10m
        max-file: "3"

volumes:
  postgresql:
    driver_opts:
      type: tmpfs
      device: tmpfs
